@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Apr 29 11:27:22 +0300 2025
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim simulate_mips_func_impl -key {Post-Implementation:sim_1:Functional:simulate_mips} -tclbatch simulate_mips.tcl -view D:/Facultate/An_II/Semestrul II/AC/Lab4_testare_mips_mem_rom/simulate_mips_func_impl.wcfg -log simulate.log"
call xsim  simulate_mips_func_impl -key {Post-Implementation:sim_1:Functional:simulate_mips} -tclbatch simulate_mips.tcl -view D:/Facultate/An_II/Semestrul II/AC/Lab4_testare_mips_mem_rom/simulate_mips_func_impl.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
